# Generated by Django 4.1.7 on 2023-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('open', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('previous_close', models.IntegerField(default=0)),
                ('current_price', models.IntegerField(default=0)),
            ],
        ),
    ]
